site_name: napari-annotatorj
site_description: The napari adaptation of the ImageJ/Fiji plugin AnnotatorJ for easy image annotation.
site_author: Reka Hollandi

theme: readthedocs


repo_url: https://github.com/spreka/napari-annotatorj

pages:
- Home: index.md
