jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: "success() && startsWith(github.ref, 'refs/tags/v*')"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: install
        run: |
          pip install -U pip
          pip install -U build twine
          python -m build

      - name: Build and publish
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY}}